gateway:
  ws:
    port: 9000
    read-timeout: 30          # 秒
    write-timeout: 5          # 秒
    ping-interval: 10         # 秒
    max-message-size: 4096    # bytes
  grpc:
    port: 9003
  http:
    port: 9004                # 健康检查
